server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos 服务地址
    sentinel:
      transport:
        dashboard: localhost:8080   #sentinel 服务地址
        port: 8719
  zipkin:
    base-url: http://localhost:9411  # zipkin 分布式链路追踪  服务地址
    sender:
      type: web     #交互方式
    discovery-client-enabled: false    #不追踪自己的请求
  sleuth:
    sampler:
      probability: 1  #sleuth 采集率 1代表百分百
 # mysql数据库和redis数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.130:3306/guli_cart
    username: root
    password: 123456
  redis:
    host: 192.168.80.130
#关闭thymeleaf 的缓存
  thymeleaf:
    cache: false
#配置线程池  搭配SpringTask 异步编程框架
  task:
    execution:
      thread-name-prefix: cart-task- # 线程池的线程名的前缀。默认为 task- ，建议根据自己应用来设置
      pool:   # 线程池相关
        core-size: 100  # 核心线程数，线程池创建时候初始化的线程数。默认为 8 。
        max-size: 500   # 最大线程数，线程池最大的线程数，只有在缓冲队列满了之后，才会申请超过核心线程数的线程。默认为 Integer.MAX_VALUE
        keep-alive: 60s  # 允许线程的空闲时间，当超过了核心线程之外的线程，在空闲时间到达之后会被销毁。默认为 60 秒
        queue-capacity: 1000  # 缓冲队列大小，用来缓冲执行任务的队列的大小。默认为 Integer.MAX_VALUE 。
        allow-core-thread-timeout: true    # 是否允许核心线程超时，即开启线程池的动态增长和缩小。默认为 true 。
      shutdown:
        await-termination: true   # 应用关闭时，是否等待(异步)定时任务执行完成。默认为 false ，建议设置为 true
        await-termination-period: 100   # 等待任务完成的最大时长，单位为秒。默认为 0 ，根据自己应用来设置
  #rabbitMQ  => 消费者
  rabbitmq:
    host: 192.168.80.130
    virtual-host: /feng
    username: admin
    password: admin
    #消费者确认机制
    # manual-手动  auto-自动（无异常直接确认，有异常无限重试） none-不重试
    listener:
      simple:
        acknowledge-mode: manual
        #能者多劳
        prefetch: 1
        #避免消息堆积,初始化多个消息线程
        concurrency: 4
feign:
  sentinel:
    enabled: true  #启用feign的 sentinel
#dao层编译后只有class文件，没有mapper.xml，
#因为maven工程在默认情况下src/main/java目录下的所有资源文件是不发布到target目录下的
#解决方法:  让maven默认加载xml文件
# 1.在pom.xml进行配置
# 2.在application.properties进行配置
#配置mapper xml文件的路径
mybatis-plus:
  #mapper-locations: classpath:mapper/ums/**/*.xml
  # 类型别名
  type-aliases-package: com.atguigu.gmall.ums.entity
  #全局id策略
  global-config:
    db-config:
      id-type: auto
#配置公钥路径,cookie名称
auth:
  jwt:
    pubKeyPath: D:\IO\rsa\rsa.pub
    cookieName: GMALL_TOKEN
    userKeyName: user_key
