server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos \u670D\u52A1\u5730\u5740
    sentinel:
      transport:
        dashboard: localhost:8080   #sentinel \u670D\u52A1\u5730\u5740
        port: 8719
  zipkin:
    base-url: http://localhost:9411  # zipkin \u5206\u5E03\u5F0F\u94FE\u8DEF\u8FFD\u8E2A  \u670D\u52A1\u5730\u5740
    sender:
      type: web     #\u4EA4\u4E92\u65B9\u5F0F
    discovery-client-enabled: false #\u4E0D\u8FFD\u8E2A\u81EA\u5DF1\u7684\u8BF7\u6C42
  sleuth:
    sampler:
      probability: 1  #sleuth \u91C7\u96C6\u7387 1\u4EE3\u8868\u767E\u5206\u767E
  # mysql\u6570\u636E\u5E93\u548Credis\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.130:3306/guli_payment
    username: root
    password: 123456
  redis:
    host: 192.168.80.130
  #\u5173\u95EDthymeleaf \u7684\u7F13\u5B58
  thymeleaf:
    cache: false
  #rabbitMQ  => \u751F\u4EA7\u8005
  rabbitmq:
    host: 192.168.80.130
    virtual-host: /feng
    username: admin
    password: admin
    publisher-returns: true
    publisher-confirm-type: simple
    #\u786E\u8BA4\u6D88\u606F\u662F\u5426\u5230\u8FBE\u4EA4\u6362\u673A:simple\u662F\u540C\u6B65\u65B9\u5F0F\u751F\u4EA7\u8005\u786E\u8BA4(\u963B\u585E) correlated\u5F02\u6B65\u786E\u8BA4
    #\u786E\u8BA4\u6D88\u606F\u662F\u5426\u5230\u8FBE\u961F\u5217
feign:
  sentinel:
    enabled: true  #\u542F\u7528feign\u7684 sentinel
#dao\u5C42\u7F16\u8BD1\u540E\u53EA\u6709class\u6587\u4EF6\uFF0C\u6CA1\u6709mapper.xml\uFF0C
#\u56E0\u4E3Amaven\u5DE5\u7A0B\u5728\u9ED8\u8BA4\u60C5\u51B5\u4E0Bsrc/main/java\u76EE\u5F55\u4E0B\u7684\u6240\u6709\u8D44\u6E90\u6587\u4EF6\u662F\u4E0D\u53D1\u5E03\u5230target\u76EE\u5F55\u4E0B\u7684
#\u89E3\u51B3\u65B9\u6CD5:  \u8BA9maven\u9ED8\u8BA4\u52A0\u8F7Dxml\u6587\u4EF6
# 1.\u5728pom.xml\u8FDB\u884C\u914D\u7F6E
# 2.\u5728application.properties\u8FDB\u884C\u914D\u7F6E
#\u914D\u7F6Emapper xml\u6587\u4EF6\u7684\u8DEF\u5F84
mybatis-plus:
  #\u5168\u5C40id\u7B56\u7565
  global-config:
    db-config:
      id-type: auto
#\u914D\u7F6E\u963F\u91CC\u652F\u4ED8\u53C2\u6570 =>\u652F\u4ED8\u5B9D\u7F51\u5173,\u5E94\u7528id,\u5546\u6237\u79C1\u94A5,\u652F\u4ED8\u5B9D\u516C\u94A5,\u670D\u52A1\u5668[\u5F02\u6B65\u901A\u77E5]\u9875\u9762\u8DEF\u5F84,\u540C\u6B65\u901A\u77E5\u652F\u4ED8\u6210\u529F
alipay:
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  app_id: 2021000118645255
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCb1iviiNelZzOlZlJ1BYkmYV5tWZSEWlF8QU39f78K46aC0XNKTpEv5SmCwYv9sQkFdMQ1ZnUJcZP+lYlMB3wotCvksrgpRN6q76xB6XGvQbHGRcxq2NN72HhJT6dDABgKx7IG1ARI8rx2t4CpctTEJ+KP3FDqBWRwRHlcXKzbe2i/Dk5KFi5IFQciDn0wPTrcqjyu5pJ2Cru09gzRmQGYyth95V7rVqfQGDbOwrl9hCLQTMIMnvErsMN+qgGf6ImBRZ2uyaiP5rkhem/zSWr0ljC0fgMQ/3xBiFXD5LAqT3Ga+Pt4w9OK5Y2MG0b+0YlTK6omNCQml0KiENoI3kQBAgMBAAECggEAO0W/1V8VHp1dQHjlvgrH+qgoQVFEMv8jZS51mojfQiYKbFF8F3RAtsXj/w7czzZp5wBdrK32sAvaLYf0+80RBW5aD5eGgnPmeX/FtiAzlGRZWL+tm6oy7jUMs12vkcVUX61K4lv78T8aPdFYB5tcn+tHuk4jHI/GfwkcW+wH90aj4+RdJRNdGxh8JeW9WNFQHCx2ZAaI12v+e057bgv8ggQ8/fdQpdmymoLVWAH8y/WmS8Cxj7CaQQ4+gwBR2L7KbXWT0FH7FwPET2TZDQCjghYqmLMizAcGuT4W8Z9alAcujUwty+XJrOON9BiyYLvtJZSFmjJu+fsuOrJELqvwrQKBgQDuVv4q8g+cmqeSiz3ZxPaf3wY+++aveXwurTGnwHN/x2YXALlfk/46WHcrf/ql0DLA55TClcGbuBDXbXbXUisXCzUwBFkhkMSeM3STCu7sJoyp9ZR1EY/Lx/B04QAvjY3dJpcbSCFlE0Mvom+K/B7/i60cGOK0G7eIw2209cSguwKBgQCnYjI+i2a0XWCQaBZzg5vgvVL0e2YLKcb8SDOR86BUmWI4EwyGHNAuaE1AuTyiCkb58RwDnAUMZPweycN4bUMpHEDJdcGydZF1l3H9tiWO/j91Eo3Jh/+F6dNcPflb0kFH//mKvi4D62UrazhWASyhCRzayDDBvGjb6nvXw0UwcwKBgDfCGkwpvQVCGRnrgVjE/31/S5LIk7tRjH/O/OLl3x9xoqyW+scldEBqGdcPZbAM+RKwGtk698RaV3ZOoZLWIkaN1K+bFM8JczYfi5Iq6KJOknHghg6tQRrHd7WgPc7iKuIl+Qvk4AspanpmYfn96bKXFrSQDdlc8p8IOU4wgQOpAoGAO5fddaEiBtM7/w3f+G6B/+jH8R1B/nV4T/fQzITlr1kQvBAkJFd70xn1bzbEHJj2HiS2qZ5RudD2ZmvFOUoFYEyb0F4pgUUUbb5mqkLAaoGgzCi37GmMEvxl8PBrqEJaVa0QBlKhhWm4klXRL+WpIwhgipA9s6xF1Q5N20q9hnsCgYAPt511kQY3JaiIS4odreNwsFphz8uMpPaxFHWoA7ZVhqPrdrsacD/AxW43cVwUwMAlEmCDWS7JnzsxIa63oyGDV+3j0D7bCfACNKKpOU5PW0nXbumMwol4uDMYduiw0sVJYObuClVzCPvqZGC7I2ogtIWm2HSCkKGDRVcEHXn65g==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhCzg+gaaAqtgKz15lNmC7wJIYwYQTbr3iQAuPUjhNahLISzD8ee8c5D0bfCTErYrm0ab8xCPGXMNapigEY8ESulrGE6xAet+kKgG/MTstneZH2jLvGhabEoo6qy8bo1D7VaXbsu6BxWsCG56vY/eXI9dEtZOxDYOY5lIJ+UHFlYGnt+UWQUg0vYzEWvDAHGicf5kOhTuxit9IJ+VlEa3bOOqQf1E5hbFNH/he7lS3+Yr/iQkVFFfxrryGmpYNr1erTbY/EV2PDF7I0ZGIT1+UrchVhObszRQvIZklKiofhP5vg+vabvujC16rQObW6VJURnCUbw5mmvuDu0yJoB+wwIDAQAB
  notify_url: http://imjinyu.free.idcfengye.com/pay/success
  return_url: http://imjinyu.free.idcfengye.com/pay/ok
#\u901A\u8FC7ngrok\u5185\u7F51\u7A7F\u900F  , \u6B64\u5904\u7528\u7684\u652F\u4ED8\u5B9D\u6C99\u7BB1\u6D4B\u8BD5



