server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos 服务地址
    sentinel:
      transport:
        dashboard: localhost:8080   #sentinel 服务地址
        port: 8719
  zipkin:
    base-url: http://localhost:9411  # zipkin 分布式链路追踪  服务地址
    sender:
      type: web    #交互方式
    discovery-client-enabled: false #不追踪自己的请求
  sleuth:
    sampler:
      probability: 1  #sleuth 采集率 1代表百分百
  # mysql数据库和redis数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.130:3306/guli_payment
    username: root
    password: 123456
  redis:
    host: 192.168.80.130
  #关闭 thymeleaf 缓存
  thymeleaf:
    cache: false
  #rabbitMQ  => 生产者
  rabbitmq:
    host: 192.168.80.130
    virtual-host: /feng
    username: admin
    password: admin
    publisher-returns: true
    publisher-confirm-type: simple
#确认消息是否到达交换机:simple是同步方式生产者确认(阻塞) correlated异步确认
#确认消息是否到达队列
feign:
  sentinel:
    enabled: true  #启用feign的 sentinel
#dao层编译后只有class文件，没有mapper.xml，
#因为maven工程在默认情况下src/main/java目录下的所有资源文件是不发布到target目录下的
#解决方法:  让maven默认加载xml文件
# 1.在pom.xml进行配置
# 2.在application.properties进行配置
#配置mapper xml文件的路径
mybatis-plus:
  #全局id策略
  global-config:
    db-config:
      id-type: auto
#配置AlipayTemplate参数 =>支付宝网关,应用的id,商户私钥,支付宝公钥,服务器[异步通知]页面路径,同步通知
alipay:
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  app_id: 2021000118645255
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCb1iviiNelZzOlZlJ1BYkmYV5tWZSEWlF8QU39f78K46aC0XNKTpEv5SmCwYv9sQkFdMQ1ZnUJcZP+lYlMB3wotCvksrgpRN6q76xB6XGvQbHGRcxq2NN72HhJT6dDABgKx7IG1ARI8rx2t4CpctTEJ+KP3FDqBWRwRHlcXKzbe2i/Dk5KFi5IFQciDn0wPTrcqjyu5pJ2Cru09gzRmQGYyth95V7rVqfQGDbOwrl9hCLQTMIMnvErsMN+qgGf6ImBRZ2uyaiP5rkhem/zSWr0ljC0fgMQ/3xBiFXD5LAqT3Ga+Pt4w9OK5Y2MG0b+0YlTK6omNCQml0KiENoI3kQBAgMBAAECggEAO0W/1V8VHp1dQHjlvgrH+qgoQVFEMv8jZS51mojfQiYKbFF8F3RAtsXj/w7czzZp5wBdrK32sAvaLYf0+80RBW5aD5eGgnPmeX/FtiAzlGRZWL+tm6oy7jUMs12vkcVUX61K4lv78T8aPdFYB5tcn+tHuk4jHI/GfwkcW+wH90aj4+RdJRNdGxh8JeW9WNFQHCx2ZAaI12v+e057bgv8ggQ8/fdQpdmymoLVWAH8y/WmS8Cxj7CaQQ4+gwBR2L7KbXWT0FH7FwPET2TZDQCjghYqmLMizAcGuT4W8Z9alAcujUwty+XJrOON9BiyYLvtJZSFmjJu+fsuOrJELqvwrQKBgQDuVv4q8g+cmqeSiz3ZxPaf3wY+++aveXwurTGnwHN/x2YXALlfk/46WHcrf/ql0DLA55TClcGbuBDXbXbXUisXCzUwBFkhkMSeM3STCu7sJoyp9ZR1EY/Lx/B04QAvjY3dJpcbSCFlE0Mvom+K/B7/i60cGOK0G7eIw2209cSguwKBgQCnYjI+i2a0XWCQaBZzg5vgvVL0e2YLKcb8SDOR86BUmWI4EwyGHNAuaE1AuTyiCkb58RwDnAUMZPweycN4bUMpHEDJdcGydZF1l3H9tiWO/j91Eo3Jh/+F6dNcPflb0kFH//mKvi4D62UrazhWASyhCRzayDDBvGjb6nvXw0UwcwKBgDfCGkwpvQVCGRnrgVjE/31/S5LIk7tRjH/O/OLl3x9xoqyW+scldEBqGdcPZbAM+RKwGtk698RaV3ZOoZLWIkaN1K+bFM8JczYfi5Iq6KJOknHghg6tQRrHd7WgPc7iKuIl+Qvk4AspanpmYfn96bKXFrSQDdlc8p8IOU4wgQOpAoGAO5fddaEiBtM7/w3f+G6B/+jH8R1B/nV4T/fQzITlr1kQvBAkJFd70xn1bzbEHJj2HiS2qZ5RudD2ZmvFOUoFYEyb0F4pgUUUbb5mqkLAaoGgzCi37GmMEvxl8PBrqEJaVa0QBlKhhWm4klXRL+WpIwhgipA9s6xF1Q5N20q9hnsCgYAPt511kQY3JaiIS4odreNwsFphz8uMpPaxFHWoA7ZVhqPrdrsacD/AxW43cVwUwMAlEmCDWS7JnzsxIa63oyGDV+3j0D7bCfACNKKpOU5PW0nXbumMwol4uDMYduiw0sVJYObuClVzCPvqZGC7I2ogtIWm2HSCkKGDRVcEHXn65g==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhCzg+gaaAqtgKz15lNmC7wJIYwYQTbr3iQAuPUjhNahLISzD8ee8c5D0bfCTErYrm0ab8xCPGXMNapigEY8ESulrGE6xAet+kKgG/MTstneZH2jLvGhabEoo6qy8bo1D7VaXbsu6BxWsCG56vY/eXI9dEtZOxDYOY5lIJ+UHFlYGnt+UWQUg0vYzEWvDAHGicf5kOhTuxit9IJ+VlEa3bOOqQf1E5hbFNH/he7lS3+Yr/iQkVFFfxrryGmpYNr1erTbY/EV2PDF7I0ZGIT1+UrchVhObszRQvIZklKiofhP5vg+vabvujC16rQObW6VJURnCUbw5mmvuDu0yJoB+wwIDAQAB
  notify_url: http://imjinyu.free.idcfengye.com/pay/success
  return_url: http://imjinyu.free.idcfengye.com/pay/ok
#此处配置ngrok内网穿透 , 支付宝沙箱操作



