server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:          #\u540D\u5B57\u7279\u610F\u4E0D\u4E00\u6837 \u4EE5\u4F5C\u533A\u5206
        - id: pms-route   #\u4EE3\u8868pms\u7684\u8DEF\u7531
          uri: lb://pms-service   #\u4EE3\u8868pms\u7684\u670D\u52A1
          predicates:
            - Path=/pms/**    #\u65AD\u8A00 \u8DEF\u5F84\u5339\u914D
        - id: sms-route   #\u4EE3\u8868pms\u7684\u8DEF\u7531
          uri: lb://sms-service   #\u4EE3\u8868pms\u7684\u670D\u52A1
          predicates:
            - Path=/sms/**    #\u65AD\u8A00 \u8DEF\u5F84\u5339\u914D
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**

