server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: pms-route  # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route   # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: oms-route   # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route   # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route   # 仓库库存管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: search-route   #搜索管理路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com  #- Path=/search/**
        - id: index-route        #首页路由
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com,gmall.com
        - id: index-route2
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route    #商品详情页的同步请求路由
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: item-route2   #商品详情页的异步请求路由
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: msm-route    #短信路由
          uri: lb://msm-service
          predicates:
            - Path=/msm/**
        - id: auth-route    #授权中心路由
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route         #购物车路由
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route        #
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
        - id: payment-route     #
          uri: lb://payment-service
          predicates:
            - Host=payment.gmall.com
          filters:
            - Auth=/pay.html,/alipay.html
        - id: payment-route2   #
          uri: lb://payment-service
          predicates:
            - Path=/pay/**
#spring.cloud.gateway:
      x-forwarded:  #当服务转发时,把域名信息通过host头信息转发给具体的服务
        host-enabled: true
#配置公钥路径,cookie名称
auth:
  jwt:
    pubKeyPath: D:\IO\rsa\rsa.pub
    cookieName: GMALL_TOKEN



