server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.80.130
#thymeleaf      取消缓存
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
#手动配置线程池的 核心线程数,最大线程数,生存时间,阻塞队列
threadPool:
  coreSize: 100
  maxSiza: 1000
  timeOut: 60
  blockingSize: 10000


