server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false #不追踪自己的请求
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
#thymeleaf      取消缓存
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
#配置公钥私钥路径,加盐,过期时间(3小时),cookie名称
auth:
  jwt:
    pubKeyPath: D:\IO\rsa\rsa.pub
    priKeyPath: D:\IO\rsa\rsa.pri
    secret: sdsag#(*)#158d@asa
    expire: 180
    cookieName: GMALL_TOKEN
    unick: unick


