server:
  port: 18081

#中间的配置信息  通过@RefreshScope 刷新读取nacos配置中心

feign:
  sentinel:
    enabled: true  #启用feign的 sentinel
#dao层编译后只有class文件，没有mapper.xml，
#因为maven工程在默认情况下src/main/java目录下的所有资源文件是不发布到target目录下的
#解决方法:  让maven默认加载xml文件
# 1.在pom.xml进行配置
# 2.在application.properties进行配置
#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:mapper/pms/**/*.xml
  # 类型别名
  type-aliases-package: com.atguigu.gmall.pms.entity
  #全局id策略
  global-config:
    db-config:
      id-type: auto
# 配置seata 分布式事务框架
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: pms-service-fescar-service-group  #需要和file.conf中的vgroupMapping对应
#rabbitMQ   => 生产者
  rabbitmq:
    host: 192.168.80.130
    virtual-host: /feng
    username: admin
    password: admin
    publisher-confirm-type: correlated   #异步
    publisher-returns: true
#确认消息是否到达交换机:simple是同步方式生产者确认(阻塞) correlated异步确认
#确认消息是否到达队列


